apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount.frontend }}
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
        - name: guestbook
          image: {{ .Values.image.frontend }}
          ports:
            - containerPort: 80

