apiVersion: v1
kind: Service
metadata:
  name: guestbook
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: guestbook

