
{{- $tls := index .Values.ingress.tls 0 }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $tls.secretName }}
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ $tls.secretName }}
  dnsNames:
    {{- range $tls.hosts }}
    - {{ . }}
    {{- end }}
  issuerRef:
    name: {{ index .Values.ingress.annotations "cert-manager.io/cluster-issuer" }}
    kind: ClusterIssuer
    group: cert-manager.io
  usages:
    - digital signature
    - key encipherment

