{{- range .Values.deployments }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  labels:
    app: {{ .name }}
    shared: "true"  
spec:
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .name }}
      shared: "true"  
  template:
    metadata:
      labels:
        app: {{ .name }}
        shared: "true"
    spec:
      containers:
        - name: {{ .name }}
          image: "{{ .image.repository }}:{{ .image.tag }}"
          imagePullPolicy: {{ .image.pullPolicy }}
          ports:
            - containerPort: 80
              name: http
          livenessProbe:
            httpGet:
              path: {{ $.Values.livenessProbe.httpGet.path }}
              port: {{ $.Values.livenessProbe.httpGet.port }}
          readinessProbe:
            httpGet:
              path: {{ $.Values.readinessProbe.httpGet.path }}
              port: {{ $.Values.readinessProbe.httpGet.port }}
      {{- if .affinity }}
      affinity:
{{ toYaml .affinity | indent 8 }}
      {{- end }}
---
{{- end }}
