apiVersion: v1
kind: Service
metadata:
  name: {{ include "task2.fullname" . }}
  labels:
    {{- include "task2.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    shared: "true"  # This will match both app1 and app2 pods
