namespace: guestbook

replicaCount:
  frontend: 3
  redisLeader: 1
  redisFollower: 2

image:
  frontend: gcr.io/google-samples/gb-frontend:v5
  redisLeader:  redis:7.2-alpine
  redisFollower: redis:7.2-alpine

service:
  type: LoadBalancer

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: ibmbook.kubeace.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - ibmbook.kubeace.com
      secretName: guestbook-tls

