replicaCount: 1

frontend:
  image: us-docker.pkg.dev/google-samples/containers/gke/gb-frontend:v5
  imagePullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 10m
      memory: 10Mi
  service:
    type: NodePort
    port: 80

redisMaster:
  image: redis:7.2-alpine
  port: 6379

redisReplica:
  image: redis:7.2-alpine
  port: 6379

