apiVersion: v1
kind: Service
metadata:
  name: redis-replica
  labels:
    app: redis
    role: replica
spec:
  ports:
  - port: {{ .Values.redisReplica.port }}
    targetPort: {{ .Values.redisReplica.port }}
  selector:
    app: redis
    role: replica

